build:
  tags:
    - bcm
  script:
    - bash /etc/profile.d/modules.sh
    - module load docker
    - mkdir -p build && latexdockercmd latexmk -output-directory=build -xelatex non_linear.tex
  artifacts:
    paths:
      - build/non_linear.pdf
