name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      uses: docker://zhaofengshu33/mini-latex:latest
      with:
        entrypoint: make
    - name: Research draft pdf
      uses: actions/upload-artifact@v1
      with:
        name: draft
        path: build/*.pdf
